id: I24B2A894
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T08:53:58+00:00'
last_modified: '2022-06-10T05:04:55.927996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30268
  title: རྒྱ་དཀར་ནག་རྒྱ་སེར་ཀཤྨི་ར་བལ་བོད་ཧོར་གྱི་ཡི་གེ་དང་དཔེ་རིས་རྣམ་གྲངས་མང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9AA9:
      image_group_id: I6022
      title: ''
      total_pages: 206
      order: 1
      base_file: 9AA9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
